name: Trivy Hub Docker Security Scan
# Controls when the action will run.
# Triggers the workflow on push or pull request
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Scan ng-devops:1.1.8 for low, Medium, High and Critical Severity
        uses: aquasecurity/trivy-action@0.7.1
        with:
          # image reference
          image-ref: chrisnt5/ng-devops:1.1.8
          # exit code when vulnerabilities were found: 0: no exit, 1: exit (means failure)
          exit-code: 0
          # severities of vulnerabilities to be displayed
          # severity: UNKNOWN,LOW,MEDIUM
          severity: LOW,MEDIUM,HIGH,CRITICAL
          
      - name: Scan hello-go:1.0.2 for low, Medium, High and Critical Severity
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: chrisnt5/hello-go:1.0.2
          exit-code: 0
          severity: LOW,MEDIUM,HIGH,CRITICAL
